stripe:
  secret_key:  	sk_test_51My8hHG5BmyqDVbtyMTUHF49p0kZ6fsdTm0pMxGCqTvPshqcLUSKavVp0j8f9BXuvyXH5tGYJYLlZXr5IxIUT7cX00uCbh4XrM
  publishable_key: pk_test_51My8hHG5BmyqDVbt7BzFKqIKOwMEfYULpTcDLRaWhcnwIMg3gYZmB3QUrI2yUIgv4KYfKCppN117kB7sPPV1KQIv00Ghd8OROh

